config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  devise_for :users, controllers: { sessions: 'users/sessions' }

  get 'welcome/:locale' => 'welcome#change_locale', as: 'change_locale'

    namespace :admin do
      get '/' => 'home#index', as: 'home'
      get '/console' => 'console#index', as: 'console'
    end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :omniauthable, :registerable,
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable

  # Virtual attribute for authenticating by either username or email
  # This is in addition to a real persisted field like 'username'
  attr_accessor :login

  validates :email, :uniqueness => true

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions.to_h).where(["username = :value OR email = :value", { :value => login.downcase }]).first
    else
      where(conditions.to_h).first
    end
  end
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  before_action :authenticate_user!
end

app/controllers/admin/console_controller.rb
class Admin::ConsoleController < Admin::BaseController

  def index

  end
end

app/controllers/admin/home_controller.rb
class Admin::HomeController < Admin::BaseController

  def index

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :initialize_for_layout

  before_action :set_locale

  def set_locale
    I18n.locale = current_user.try(:locale) || cookies[:locale] || LocalLocales.find(extract_locale_from_accept_language_header)
  end

  private

  def after_sign_in_path_for(resource)
    sign_in_url = new_user_session_url
    if request.referer == sign_in_url
      admin_home_path
    else
      stored_location_for(resource) || request.referer || root_path
    end
  end

  def store_locale
    cookies[:locale] = params[:locale]
    current_user.try(:update_column, :locale, cookies[:locale])
  end

  def extract_locale_from_accept_language_header
    request.env['HTTP_ACCEPT_LANGUAGE'].scan(/^[a-z]{2}/).first
  end

  def initialize_for_layout
    @menu_manager = GlobalMenu::Manager.new

    @menu_manager.for_container(t('menu.admin'), admin_home_path) do |admin_container|
      admin_container << GlobalMenu::Item.new(t('menu.console'), admin_console_path)
    end if user_signed_in?
  end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
# before_filter :configure_sign_up_params, only: [:create]
# before_filter :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.for(:sign_up) << :attribute
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.for(:account_update) << :attribute
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  def create
    cookies[:locale] = current_user.locale if current_user && current_user.locale.present?
    super
  end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def change_locale
    fail 'Invalid locale' unless LocalLocales.is_supported?(params[:locale])

    store_locale
    set_locale

    redirect_to :back
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_locale?(locale)
    locale.to_s.downcase == I18n.locale
  end

  def loginout_link
    (user_signed_in? ? link_to(t(:logout), destroy_user_session_path, method: :delete) : link_to(t(:login), new_user_session_path))
  end

  def global_menus
    GlobalMenu.each do |menu_container, menu_items|
      yield menu_container, menu_items
    end
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/console/index.slim
.container
  h1
    = t('menu.console')

app/views/admin/home/index.slim
.container
  h1
    = t('menu.admin')

app/views/layouts/application.slim
doctype html

html
  head
    meta[http-equiv="Content-Type" content="text/html; charset=UTF-8"]
    meta[name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no"]
    title
      = t(:logo)
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = stylesheet_link_tag 'https://fonts.googleapis.com/icon?family=Material+Icons', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    = render 'shared/nav_main'

    = yield

    = hidden_field_tag(:flash_notice, notice)
    = hidden_field_tag(:flash_alert, alert)

    = javascript_include_tag 'application', 'data-turbolinks-track' => true

app/views/shared/_footer.slim
footer.page-footer
  .container
    .row
      .col.l6.s12
        h5.white-text Company Bio

        p.grey-text.text-lighten-4 We are a team of college students working on this project like it's our full
          | time job. Any amount would help support and continue development on this project and is greatly
          | appreciated.

      .col.l3.s12
        h5.white-text Settings
        ul
          li
            a.white-text[href="#!"] Link 1
          li
            a.white-text[href="#!"] Link 2
      .col.l3.s12
        h5.white-text Connect
        ul
          li
            a.white-text[href="#!"] Link 1
          li
            a.white-text[href="#!"] Link 2

  .footer-copyright
    .container
      | Made by
      a.brown-text.text-lighten-3[href="http://materializecss.com"] Materialize

app/views/shared/_nav_main.slim
ul#dropdown1.dropdown-content
  - LocalLocales.each do |locale|
    li
      = link_to(locale.upcase, change_locale_path(locale))

- @menu_manager.each_container do |container|
  = content_tag(:ul, id: "dd-#{container.lookup}", class:'dropdown-content')
    - container.each_item do |menu_item|
      li
       = link_to(menu_item.name, menu_item.path)

nav(role="navigation")
  .nav-wrapper.container
    = link_to t(:logo), root_path, class: 'logo-container brand-logo'
    ul.right.hide-on-med-and-down
      - @menu_manager.each_container do |container|
        li
          = link_to(container.caption, container.path, :'data-activates' => "dd-#{container.lookup}", class: 'global-nav-dropdown-button')
      li
        = loginout_link
      li
        a.global-nav-dropdown-button(href="javascript:void(0)" data-activates="dropdown1")
          i.tiny.material-icons language

    ul#nav-mobile.side-nav
      - @menu_manager.each_container do |container|
        - container.each_item do |menu_item|
          li
            = link_to(menu_item.name, menu_item.path)

        li.divider
      li
        = loginout_link
      li.divider
      - LocalLocales.each do |locale|
        li
          = link_to(locale.upcase, change_locale_path(locale))
    a.button-collapse(href="#" data-activates="nav-mobile")
      i.material-icons menu

app/views/welcome/index.slim
= stylesheet_link_tag params[:controller]
= javascript_include_tag params[:controller]

#index-banner.parallax-container
  .section.no-pad-bot
    .container
      /br
      /br
      /h1.header.center.text-lighten-2
      /  | Parallax Template
      /.row.center
      /  h5.header.col.s12.light.black-text
      /    | A modern responsive front-end framework based on Material Design
      /.row.center
      /  a#download-button.btn-large.waves-effect.waves-light.teal.lighten-1[href="http://materializecss.com/getting-started.html"]
      /    | Get Started
      /br
      /br
  .parallax
    = image_tag('background1.jpg')
.container
  .section
    .row
      .col.s12.m4
        .icon-block
          h2.center.brown-text
            i.material-icons
              | flash_on
          h5.center
            = t('.c1_header')
          p.light
            = t('.c1_content')
      .col.s12.m4
        .icon-block
          h2.center.brown-text
            i.material-icons
              | group
          h5.center
            = t('.c2_header')
          p.light
            = t('.c2_content')
      .col.s12.m4
        .icon-block
          h2.center.brown-text
            i.material-icons
              | settings
          h5.center
            = t('.c3_header')
          p.light
            = t('.c3_content')
.parallax-container.valign-wrapper
  .section.no-pad-bot
    .container
      .row.center
        h5.header.col.s12.light
          | A modern responsive front-end framework based on Material Design
  .parallax
    = image_tag('background2.jpg')
.container
  .section
    .row
      .col.s12.center
        h3
          i.mdi-content-send.brown-text
        h4
          | Contact Us
        p.left-align.light
          | Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam scelerisque id nunc nec volutpat. Etiam pellentesque tristique arcu, non consequat magna fermentum ac. Cras ut ultricies eros. Maecenas eros justo, ullamcorper a sapien id, viverra ultrices eros. Morbi sem neque, posuere et pretium eget, bibendum sollicitudin lacus. Aliquam eleifend sollicitudin diam, eu mattis nisl maximus sed. Nulla imperdiet semper molestie. Morbi massa odio, condimentum sed ipsum ac, gravida ultrices erat. Nullam eget dignissim mauris, non tristique erat. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae;
.parallax-container.valign-wrapper
  .section.no-pad-bot
    .container
      .row.center
        h5.header.col.s12.light
          | A modern responsive front-end framework based on Material Design
  .parallax
    = image_tag('background3.jpg')

= render 'shared/footer' unless @suppress_footer